FROM ubuntu:bionic

WORKDIR /opt/

COPY requirements.sys requirements.sys
RUN apt update && xargs apt install -y < requirements.sys

## install gtest
RUN wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz && \
    tar -zxvf release-1.10.0.tar.gz && rm release-1.10.0.tar.gz && \
    cd googletest-release-1.10.0 && mkdir -p build && cd build && cmake .. && make install 

WORKDIR /app/

COPY include /app/include
COPY examples /app/examples
COPY tests /app/tests
COPY CMakeLists.txt CMakeLists.txt

RUN mkdir -p build && cd build && cmake -DBUILD_EXAMPLES=ON .. && make

CMD ["/app/build/tests/trjtools-test"]